### ISSUE TITLE
feat: show time api

### ISSUE THREAD

**Issue by Minhquanzz1002** [Minhquanzz1002/cinema-web#22]
## Tasks
- [x] display show times timeline
- [x] create show time
- [x] update show time 
- [x] delete show time
