### ISSUE TITLE
feat: product price view

### ISSUE THREAD

**Issue by Minhquanzz1002** [Minhquanzz1002/cinema-web#35]
# Tasks

- [x] fix: status
- [ ] feat: view list product price
- [ ] feat: add product price
- [ ] feat: delete product price
- [ ] feat: update product price
